quarkus.http.root-path=/api
quarkus.package.jar.type=uber-jar

quarkus.http.host = 0.0.0.0

quarkus.devservices.enabled=false

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=4DK88W61f56a17xK
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/friedhofverwaltung
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/friedhofverwaltung

quarkus.hibernate-orm.database.generation=drop-and-create
%prod.quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.database.generation.halt-on-error=false
quarkus.hibernate-orm.sql-load-script=db/import.sql
quarkus.datasource.devservices.enabled=false
quarkus.hibernate-orm.log.sql=true
quarkus.http.access-log.enabled=true

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:4200, http://localhost:8080
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.exposed-headers=location,info
quarkus.http.cors.access-control-allow-credentials=true